import fontkit from "@pdf-lib/fontkit";
import { PDFDocument, rgb } from "pdf-lib";
import { shapeArabic } from "@/lib/secure-view/arabic-shaper";
import { watermarkFontBytes } from "@/lib/secure-view/watermark-font";
import { writeFileSync } from "node:fs";
const shaped = shapeArabic("تاريخ الإصدار: 2026-08-04");
const doc = await PDFDocument.create();
doc.registerFontkit(fontkit);
const font = await doc.embedFont(watermarkFontBytes(), { subset: true });
const full = doc.addPage([400, 80]);
full.drawText(shaped, { x: 20, y: 30, size: 18, font, color: rgb(0, 0, 0) });
const dateOnly = doc.addPage([400, 80]);
dateOnly.drawText("2026-08-04", { x: 20, y: 30, size: 18, font, color: rgb(0, 0, 0) });
writeFileSync("/tmp/pdfqa/calib2.pdf", await doc.save());
console.log("date width", font.widthOfTextAtSize("2026-08-04", 18));
