/**
 * قوالب الأدوار التشغيلية — نقطة بداية قابلة للنسخ والتعديل، وليست أدواراً إلزامية.
 *
 * قواعد ملزمة:
 *  - القالب لا يُنشئ صلاحية جديدة؛ كل مفتاح هنا موجود في `ADMIN_PERMISSIONS`.
 *  - القالب لا يُسند تلقائياً لأي موظف؛ يُنسخ إلى دور في `platform_roles` بطلب صريح.
 *  - نسخ القالب يمر بنفس حراسة عدم التصعيد في `saveRole`: لا يمنح المُنشئ
 *    صلاحية لا يملكها، ويُبلَّغ عن الصلاحيات المحجوبة بدل تمريرها بصمت.
 *  - `Owner / super_admin` وحده غير المقيد، ولا يوجد قالب يعادله.
 *
 * هذا الملف آمن للمتصفح (بيانات فقط) ويُستخدم في الواجهة والخادم معاً.
 */
import type { AdminPermission } from "@/lib/admin-permissions";

export type RoleTemplateTier = "operations" | "commercial" | "governance" | "readonly";

export interface RoleTemplate {
  /** رمز مقترح للدور الناتج — يُعدّله المستخدم عند النسخ إن أراد. */
  code: string;
  name_ar: string;
  name_en: string;
  tier: RoleTemplateTier;
  summary: string;
  permissions: AdminPermission[];
}

export const ROLE_TEMPLATE_TIER_LABELS: Record<RoleTemplateTier, string> = {
  operations: "التشغيل والتقنية",
  commercial: "التجاري والمالي",
  governance: "الحوكمة والأمان",
  readonly: "الاطلاع فقط",
};

export const ROLE_TEMPLATES: RoleTemplate[] = [
  {
    code: "platform_administrator",
    name_ar: "مدير المنصة",
    name_en: "Platform Administrator",
    tier: "governance",
    summary:
      "إدارة تشغيلية واسعة للمنصة وفريقها وأدوارها، دون عمليات الحذف النهائي ولا الاستردادات المالية ولا استعادة النسخ.",
    permissions: [
      "users.read",
      "users.create",
      "users.update",
      "organizations.read",
      "organizations.update",
      "subscriptions.manage",
      "plans.manage",
      "revenue.read",
      "platform_settings.read",
      "platform_settings.manage",
      "feature_flags.read",
      "feature_flags.manage",
      "notification_rules.read",
      "notification_rules.manage",
      "content.read",
      "content.manage",
      "content.publish",
      "design.read",
      "design.manage",
      "seo.read",
      "seo.manage",
      "integrations.read",
      "integrations.test",
      "integrations.view_logs",
      "monitoring.read",
      "monitoring.export",
      "backups.read",
      "backups.manage",
      "notifications.send",
      "audit.read",
      "staff.view",
      "staff.manage",
      "rbac.read",
      "roles.manage",
      "departments.read",
      "departments.manage",
      "staff.sessions.read",
      "approvals.request",
      "approvals.decide",
      "delegation.grant",
      "delegation.revoke",
    ],
  },
  {
    code: "operations_manager",
    name_ar: "مدير العمليات",
    name_en: "Operations Manager",
    tier: "operations",
    summary: "تشغيل المنصة اليومي: المراقبة والمهام ومفاتيح التشغيل وقواعد الإشعارات وسجل النسخ.",
    permissions: [
      "users.read",
      "organizations.read",
      "monitoring.read",
      "monitoring.export",
      "feature_flags.read",
      "feature_flags.manage",
      "notification_rules.read",
      "notification_rules.manage",
      "notifications.send",
      "integrations.read",
      "integrations.test",
      "integrations.view_logs",
      "backups.read",
      "backups.manage",
      "email.read",
      "email.retry",
      "email.view_logs",
      "sms.read",
      "platform_settings.read",
      "audit.read",
      "approvals.request",
    ],
  },
  {
    code: "support_manager",
    name_ar: "مدير الدعم",
    name_en: "Support Manager",
    tier: "operations",
    summary: "إدارة مركز الدعم كاملاً: المهل والفرق والتصنيفات والدمج والتقارير عبر جميع المكاتب.",
    permissions: [
      "support.read",
      "support.create",
      "support.reply",
      "support.assign",
      "support.escalate",
      "support.close",
      "support.reopen",
      "support.merge",
      "support.manage_sla",
      "support.manage_categories",
      "support.view_all_offices",
      "support.export",
      "support_access.request",
      "users.read",
      "organizations.read",
      "email.view",
      "email.send",
      "email.assign",
      "audit.read",
      "approvals.request",
    ],
  },
  {
    code: "support_agent",
    name_ar: "أخصائي دعم",
    name_en: "Support Agent",
    tier: "operations",
    summary:
      "معالجة التذاكر المسندة إليه وإلى فرقه فقط، بلا إدارة مهل ولا دمج ولا اطلاع على كل المكاتب.",
    permissions: [
      "support.read",
      "support.create",
      "support.reply",
      "support.assign",
      "support.escalate",
      "support.close",
      "users.read",
      "organizations.read",
      "email.view",
      "email.send",
    ],
  },
  {
    code: "finance_manager",
    name_ar: "المدير المالي",
    name_en: "Finance Manager",
    tier: "commercial",
    summary:
      "المركز المالي كاملاً: الإصدار والاعتماد والاسترداد والمطابقة والإقفال. إعادة فتح الفترات تحتاج اعتماد موظف آخر.",
    permissions: [
      "billing.read",
      "billing.create",
      "billing.update",
      "billing.issue",
      "billing.cancel",
      "billing.record_payment",
      "billing.approve_payment",
      "billing.refund",
      "billing.export",
      "billing.reconcile",
      "billing.close_period",
      "billing.view_reports",
      "revenue.read",
      "subscriptions.manage",
      "plans.manage",
      "organizations.read",
      "users.read",
      "audit.read",
      "approvals.request",
    ],
  },
  {
    code: "accountant",
    name_ar: "محاسب",
    name_en: "Accountant",
    tier: "commercial",
    summary:
      "إعداد الفواتير وتسجيل الدفعات والمطابقة والتقارير، دون إصدار نهائي ولا إلغاء ولا استرداد.",
    permissions: [
      "billing.read",
      "billing.create",
      "billing.update",
      "billing.record_payment",
      "billing.export",
      "billing.reconcile",
      "billing.view_reports",
      "revenue.read",
      "organizations.read",
    ],
  },
  {
    code: "sales_manager",
    name_ar: "مدير المبيعات",
    name_en: "Sales Manager",
    tier: "commercial",
    summary:
      "إدارة خط البيع كاملاً: علاقات العملاء والمراحل والعروض والعقود واعتمادها وتحويلها لفواتير.",
    permissions: [
      "crm.read",
      "crm.create",
      "crm.update",
      "crm.assign",
      "crm.export",
      "crm.manage_pipeline",
      "sales_docs.read",
      "sales_docs.create",
      "sales_docs.update",
      "sales_docs.send",
      "sales_docs.approve",
      "sales_docs.decide",
      "sales_docs.convert",
      "sales_docs.manage_templates",
      "sales_docs.export",
      "organizations.read",
      "users.read",
      "revenue.read",
      "billing.read",
      "approvals.request",
    ],
  },
  {
    code: "sales_representative",
    name_ar: "مندوب مبيعات",
    name_en: "Sales Representative",
    tier: "commercial",
    summary:
      "متابعة العملاء المحتملين والصفقات وإعداد العروض وإرسالها، دون اعتماد ولا تحويل لفواتير ولا حذف.",
    permissions: [
      "crm.read",
      "crm.create",
      "crm.update",
      "crm.export",
      "sales_docs.read",
      "sales_docs.create",
      "sales_docs.update",
      "sales_docs.send",
      "sales_docs.export",
      "organizations.read",
    ],
  },
  {
    code: "marketing_manager",
    name_ar: "مدير التسويق",
    name_en: "Marketing Manager",
    tier: "commercial",
    summary:
      "الحملات والإحالات وأحداث التحويل، مع تحرير محتوى تسويقي وإعدادات SEO وإرسال الإشعارات.",
    permissions: [
      "marketing.read",
      "marketing.manage",
      "marketing.export",
      "crm.read",
      "crm.export",
      "content.read",
      "content.manage",
      "seo.read",
      "seo.manage",
      "notifications.send",
      "revenue.read",
      "organizations.read",
    ],
  },
  {
    code: "content_editor",
    name_ar: "محرّر محتوى",
    name_en: "Content Editor",
    tier: "operations",
    summary: "تحرير مسوّدات الصفحات النظامية فقط. لا نشر ولا تراجع ولا تعديل تصميم.",
    permissions: ["content.read", "content.manage", "design.read", "seo.read"],
  },
  {
    code: "content_publisher",
    name_ar: "ناشر محتوى",
    name_en: "Content Publisher",
    tier: "operations",
    summary: "نشر المسوّدات والتراجع عن النشر وإدارة التصميم وSEO — فصل صريح عن التحرير.",
    permissions: [
      "content.read",
      "content.manage",
      "content.publish",
      "content.rollback",
      "design.read",
      "design.manage",
      "seo.read",
      "seo.manage",
    ],
  },
  {
    code: "hr_manager",
    name_ar: "مدير الموارد البشرية",
    name_en: "HR Manager",
    tier: "governance",
    summary:
      "ملفات موظفي المنصة ومستنداتهم وهيكل الأقسام، دون أي صلاحية على بيانات المكاتب أو المال.",
    permissions: [
      "hr.read",
      "hr.manage",
      "hr.documents.read",
      "staff.view",
      "departments.read",
      "audit.read",
    ],
  },
  {
    code: "legal_manager",
    name_ar: "المدير القانوني",
    name_en: "Legal Manager",
    tier: "governance",
    summary: "حوكمة العقود والمقترحات: اعتمادها وقوالبها وتصديرها، مع الاطلاع على سجل التدقيق.",
    permissions: [
      "sales_docs.read",
      "sales_docs.update",
      "sales_docs.approve",
      "sales_docs.decide",
      "sales_docs.manage_templates",
      "sales_docs.export",
      "content.read",
      "organizations.read",
      "audit.read",
      "approvals.request",
    ],
  },
  {
    code: "contract_reviewer",
    name_ar: "مراجع عقود",
    name_en: "Contract Reviewer",
    tier: "governance",
    summary: "مراجعة نصوص العقود وتعديل المسوّدات فقط، بلا اعتماد ولا إرسال ولا تحويل.",
    permissions: [
      "sales_docs.read",
      "sales_docs.update",
      "sales_docs.export",
      "organizations.read",
    ],
  },
  {
    code: "technical_operations",
    name_ar: "التشغيل التقني",
    name_en: "Technical Operations",
    tier: "operations",
    summary:
      "صحة التكاملات والبريد والرسائل والمراقبة. تفعيل التكاملات مسموح؛ حفظ أسرارها ليس ضمن القالب.",
    permissions: [
      "monitoring.read",
      "monitoring.export",
      "integrations.read",
      "integrations.test",
      "integrations.activate",
      "integrations.view_logs",
      "email.read",
      "email.retry",
      "email.view_logs",
      "email.manage_providers",
      "email.manage_mailboxes",
      "sms.read",
      "backups.read",
      "backups.manage",
      "platform_settings.read",
      "audit.read",
    ],
  },
  {
    code: "security_administrator",
    name_ar: "مسؤول الأمان",
    name_en: "Security Administrator",
    tier: "governance",
    summary:
      "مركز الأمان ومفاتيح التشفير والجلسات والقيود واعتماد الانتحال وتصدير أحداث الأمان. لا صلاحيات مالية ولا تجارية.",
    permissions: [
      "security.read",
      "security.manage",
      "security.sessions.manage",
      "security.events.export",
      "staff.sessions.read",
      "staff.sessions.revoke",
      "staff.restrictions.manage",
      "rbac.read",
      "audit.read",
      "audit.export",
      "approvals.decide",
      "impersonation.approve",
      "delegation.revoke",
      "monitoring.read",
    ],
  },
  {
    code: "auditor",
    name_ar: "مدقّق",
    name_en: "Auditor",
    tier: "readonly",
    summary: "اطلاع وتصدير للتدقيق فقط — لا يملك أي صلاحية كتابة على أي وحدة.",
    permissions: [
      "audit.read",
      "audit.export",
      "rbac.read",
      "staff.view",
      "staff.sessions.read",
      "monitoring.read",
      "security.read",
      "billing.read",
      "billing.view_reports",
      "revenue.read",
      "organizations.read",
      "users.read",
      "support.read",
    ],
  },
  {
    code: "executive_viewer",
    name_ar: "اطلاع تنفيذي",
    name_en: "Executive Viewer",
    tier: "readonly",
    summary: "مؤشرات الأعمال والتقارير عبر الوحدات للقيادة التنفيذية، بلا أي كتابة.",
    permissions: [
      "revenue.read",
      "billing.read",
      "billing.view_reports",
      "monitoring.read",
      "organizations.read",
      "users.read",
      "crm.read",
      "marketing.read",
      "sales_docs.read",
      "support.read",
      "hr.read",
    ],
  },
  {
    code: "read_only",
    name_ar: "اطلاع فقط",
    name_en: "Read Only",
    tier: "readonly",
    summary: "أدنى مستوى وصول: قراءة الوحدات التشغيلية العامة دون أي بيانات أمنية أو مالية حساسة.",
    permissions: [
      "users.read",
      "organizations.read",
      "crm.read",
      "sales_docs.read",
      "marketing.read",
      "hr.read",
      "support.read",
      "billing.read",
      "monitoring.read",
      "backups.read",
      "content.read",
      "design.read",
      "seo.read",
      "integrations.read",
      "feature_flags.read",
      "notification_rules.read",
      "platform_settings.read",
      "rbac.read",
    ],
  },
];

export const ROLE_TEMPLATE_MAP: Record<string, RoleTemplate> = Object.fromEntries(
  ROLE_TEMPLATES.map((t) => [t.code, t]),
);

/** الفرق بين قالبين — لعرض مقارنة صريحة في الواجهة. */
export function diffTemplates(
  a: RoleTemplate,
  b: RoleTemplate,
): { onlyA: string[]; onlyB: string[]; shared: string[] } {
  const setA = new Set<string>(a.permissions);
  const setB = new Set<string>(b.permissions);
  return {
    onlyA: a.permissions.filter((p) => !setB.has(p)),
    onlyB: b.permissions.filter((p) => !setA.has(p)),
    shared: a.permissions.filter((p) => setB.has(p)),
  };
}
