import { office, one, payload, fixtureBase64 } from "./lib";
import { setupEnv, SLUG_A } from "./setup";
import { snapshotA } from "./content";
const env = await setupEnv();
await office("changeOfficePageSlug", env.ownerA.token, { organizationId: env.orgA, slug: SLUG_A });
const up = async (kind: string, ct: string, f: string) => {
  const r = await office("uploadOfficePageMedia", env.ownerA.token, { organizationId: env.orgA, kind, contentType: ct, base64: await fixtureBase64(f) });
  return payload<{ path?: string }>(r.raw)?.path ?? `ERR:${r.message}`;
};
const logoPath = await up("logo", "image/jpeg", "logo.jpg");
const coverPath = await up("cover", "image/png", "cover.png");
console.log({ logoPath, coverPath });
await office("saveOfficePageDraft", env.ownerA.token, { organizationId: env.orgA, draft: snapshotA({ logo_path: logoPath, cover_path: coverPath }) });
console.log("pub1", (await office("publishOfficePage", env.ownerA.token, { organizationId: env.orgA })).message || "ok");
const row = await one(`office_public_pages?select=version,published&organization_id=eq.${env.orgA}`);
const p = row!["published"] as any;
console.log("v", row!["version"], p.logo_path, p.cover_path);
await office("saveOfficePageDraft", env.ownerA.token, { organizationId: env.orgA, draft: snapshotA({ logo_path: p.logo_path, cover_path: p.cover_path }) });
const rp = await office("publishOfficePage", env.ownerA.token, { organizationId: env.orgA });
console.log("pub2", rp.ok, rp.message);
const row2 = await one(`office_public_pages?select=version,published&organization_id=eq.${env.orgA}`);
console.log("v2", row2!["version"], (row2!["published"] as any).logo_path);
