/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PendingAccessRouteImport } from './routes/pending-access'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as MehlaAdminRouteRouteImport } from './routes/mehla-admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadIndexRouteImport } from './routes/upload.index'
import { Route as MehlaAdminIndexRouteImport } from './routes/mehla-admin/index'
import { Route as UploadTokenRouteImport } from './routes/upload.$token'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as MehlaAdminUsersRouteImport } from './routes/mehla-admin/users'
import { Route as MehlaAdminSupportRouteImport } from './routes/mehla-admin/support'
import { Route as MehlaAdminSubscriptionsRouteImport } from './routes/mehla-admin/subscriptions'
import { Route as MehlaAdminStaffRouteImport } from './routes/mehla-admin/staff'
import { Route as MehlaAdminSmsRouteImport } from './routes/mehla-admin/sms'
import { Route as MehlaAdminSettingsRouteImport } from './routes/mehla-admin/settings'
import { Route as MehlaAdminSeoRouteImport } from './routes/mehla-admin/seo'
import { Route as MehlaAdminSecurityRouteImport } from './routes/mehla-admin/security'
import { Route as MehlaAdminRolesRouteImport } from './routes/mehla-admin/roles'
import { Route as MehlaAdminRevenueRouteImport } from './routes/mehla-admin/revenue'
import { Route as MehlaAdminPlansRouteImport } from './routes/mehla-admin/plans'
import { Route as MehlaAdminOrganizationsRouteImport } from './routes/mehla-admin/organizations'
import { Route as MehlaAdminNotificationsRouteImport } from './routes/mehla-admin/notifications'
import { Route as MehlaAdminMonitoringRouteImport } from './routes/mehla-admin/monitoring'
import { Route as MehlaAdminLogsRouteImport } from './routes/mehla-admin/logs'
import { Route as MehlaAdminFailuresRouteImport } from './routes/mehla-admin/failures'
import { Route as MehlaAdminEmailRouteImport } from './routes/mehla-admin/email'
import { Route as AuthVerifiedRouteImport } from './routes/auth.verified'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedPrintLogRouteImport } from './routes/_authenticated/print-log'
import { Route as AuthenticatedHearingsRouteImport } from './routes/_authenticated/hearings'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDeadlinesRouteImport } from './routes/_authenticated/deadlines'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated/cases.index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedCasesIdRouteImport } from './routes/_authenticated/cases.$id'
import { Route as ApiPublicHooksCleanupSecureArtifactsRouteImport } from './routes/api/public/hooks/cleanup-secure-artifacts'
import { Route as ApiPublicDocTokenRouteImport } from './routes/api/public/doc.$token'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingAccessRoute = PendingAccessRouteImport.update({
  id: '/pending-access',
  path: '/pending-access',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const MehlaAdminRouteRoute = MehlaAdminRouteRouteImport.update({
  id: '/mehla-admin',
  path: '/mehla-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadIndexRoute = UploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const MehlaAdminIndexRoute = MehlaAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MehlaAdminUsersRoute = MehlaAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSupportRoute = MehlaAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSubscriptionsRoute = MehlaAdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminStaffRoute = MehlaAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSmsRoute = MehlaAdminSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSettingsRoute = MehlaAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSeoRoute = MehlaAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSecurityRoute = MehlaAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminRolesRoute = MehlaAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminRevenueRoute = MehlaAdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminPlansRoute = MehlaAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminOrganizationsRoute = MehlaAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminNotificationsRoute = MehlaAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminMonitoringRoute = MehlaAdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminLogsRoute = MehlaAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminFailuresRoute = MehlaAdminFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminEmailRoute = MehlaAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/auth/verified',
  path: '/auth/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintLogRoute = AuthenticatedPrintLogRouteImport.update({
  id: '/print-log',
  path: '/print-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHearingsRoute = AuthenticatedHearingsRouteImport.update({
  id: '/hearings',
  path: '/hearings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeadlinesRoute = AuthenticatedDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCasesIdRoute = AuthenticatedCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksCleanupSecureArtifactsRoute =
  ApiPublicHooksCleanupSecureArtifactsRouteImport.update({
    id: '/api/public/hooks/cleanup-secure-artifacts',
    path: '/api/public/hooks/cleanup-secure-artifacts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDocTokenRoute = ApiPublicDocTokenRouteImport.update({
  id: '/api/public/doc/$token',
  path: '/api/public/doc/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mehla-admin': typeof MehlaAdminRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-access': typeof PendingAccessRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/hearings': typeof AuthenticatedHearingsRoute
  '/print-log': typeof AuthenticatedPrintLogRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/mehla-admin/email': typeof MehlaAdminEmailRoute
  '/mehla-admin/failures': typeof MehlaAdminFailuresRoute
  '/mehla-admin/logs': typeof MehlaAdminLogsRoute
  '/mehla-admin/monitoring': typeof MehlaAdminMonitoringRoute
  '/mehla-admin/notifications': typeof MehlaAdminNotificationsRoute
  '/mehla-admin/organizations': typeof MehlaAdminOrganizationsRoute
  '/mehla-admin/plans': typeof MehlaAdminPlansRoute
  '/mehla-admin/revenue': typeof MehlaAdminRevenueRoute
  '/mehla-admin/roles': typeof MehlaAdminRolesRoute
  '/mehla-admin/security': typeof MehlaAdminSecurityRoute
  '/mehla-admin/seo': typeof MehlaAdminSeoRoute
  '/mehla-admin/settings': typeof MehlaAdminSettingsRoute
  '/mehla-admin/sms': typeof MehlaAdminSmsRoute
  '/mehla-admin/staff': typeof MehlaAdminStaffRoute
  '/mehla-admin/subscriptions': typeof MehlaAdminSubscriptionsRoute
  '/mehla-admin/support': typeof MehlaAdminSupportRoute
  '/mehla-admin/users': typeof MehlaAdminUsersRoute
  '/share/$token': typeof ShareTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/mehla-admin/': typeof MehlaAdminIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/cases/$id': typeof AuthenticatedCasesIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/cases/': typeof AuthenticatedCasesIndexRoute
  '/api/public/doc/$token': typeof ApiPublicDocTokenRoute
  '/api/public/hooks/cleanup-secure-artifacts': typeof ApiPublicHooksCleanupSecureArtifactsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-access': typeof PendingAccessRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/hearings': typeof AuthenticatedHearingsRoute
  '/print-log': typeof AuthenticatedPrintLogRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/mehla-admin/email': typeof MehlaAdminEmailRoute
  '/mehla-admin/failures': typeof MehlaAdminFailuresRoute
  '/mehla-admin/logs': typeof MehlaAdminLogsRoute
  '/mehla-admin/monitoring': typeof MehlaAdminMonitoringRoute
  '/mehla-admin/notifications': typeof MehlaAdminNotificationsRoute
  '/mehla-admin/organizations': typeof MehlaAdminOrganizationsRoute
  '/mehla-admin/plans': typeof MehlaAdminPlansRoute
  '/mehla-admin/revenue': typeof MehlaAdminRevenueRoute
  '/mehla-admin/roles': typeof MehlaAdminRolesRoute
  '/mehla-admin/security': typeof MehlaAdminSecurityRoute
  '/mehla-admin/seo': typeof MehlaAdminSeoRoute
  '/mehla-admin/settings': typeof MehlaAdminSettingsRoute
  '/mehla-admin/sms': typeof MehlaAdminSmsRoute
  '/mehla-admin/staff': typeof MehlaAdminStaffRoute
  '/mehla-admin/subscriptions': typeof MehlaAdminSubscriptionsRoute
  '/mehla-admin/support': typeof MehlaAdminSupportRoute
  '/mehla-admin/users': typeof MehlaAdminUsersRoute
  '/share/$token': typeof ShareTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/mehla-admin': typeof MehlaAdminIndexRoute
  '/upload': typeof UploadIndexRoute
  '/cases/$id': typeof AuthenticatedCasesIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/api/public/doc/$token': typeof ApiPublicDocTokenRoute
  '/api/public/hooks/cleanup-secure-artifacts': typeof ApiPublicHooksCleanupSecureArtifactsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/mehla-admin': typeof MehlaAdminRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-access': typeof PendingAccessRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deadlines': typeof AuthenticatedDeadlinesRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/hearings': typeof AuthenticatedHearingsRoute
  '/_authenticated/print-log': typeof AuthenticatedPrintLogRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/mehla-admin/email': typeof MehlaAdminEmailRoute
  '/mehla-admin/failures': typeof MehlaAdminFailuresRoute
  '/mehla-admin/logs': typeof MehlaAdminLogsRoute
  '/mehla-admin/monitoring': typeof MehlaAdminMonitoringRoute
  '/mehla-admin/notifications': typeof MehlaAdminNotificationsRoute
  '/mehla-admin/organizations': typeof MehlaAdminOrganizationsRoute
  '/mehla-admin/plans': typeof MehlaAdminPlansRoute
  '/mehla-admin/revenue': typeof MehlaAdminRevenueRoute
  '/mehla-admin/roles': typeof MehlaAdminRolesRoute
  '/mehla-admin/security': typeof MehlaAdminSecurityRoute
  '/mehla-admin/seo': typeof MehlaAdminSeoRoute
  '/mehla-admin/settings': typeof MehlaAdminSettingsRoute
  '/mehla-admin/sms': typeof MehlaAdminSmsRoute
  '/mehla-admin/staff': typeof MehlaAdminStaffRoute
  '/mehla-admin/subscriptions': typeof MehlaAdminSubscriptionsRoute
  '/mehla-admin/support': typeof MehlaAdminSupportRoute
  '/mehla-admin/users': typeof MehlaAdminUsersRoute
  '/share/$token': typeof ShareTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/mehla-admin/': typeof MehlaAdminIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/_authenticated/cases/$id': typeof AuthenticatedCasesIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
  '/api/public/doc/$token': typeof ApiPublicDocTokenRoute
  '/api/public/hooks/cleanup-secure-artifacts': typeof ApiPublicHooksCleanupSecureArtifactsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mehla-admin'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/pending-access'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/clients'
    | '/dashboard'
    | '/deadlines'
    | '/documents'
    | '/hearings'
    | '/print-log'
    | '/search'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/tasks'
    | '/team'
    | '/auth/callback'
    | '/auth/verified'
    | '/mehla-admin/email'
    | '/mehla-admin/failures'
    | '/mehla-admin/logs'
    | '/mehla-admin/monitoring'
    | '/mehla-admin/notifications'
    | '/mehla-admin/organizations'
    | '/mehla-admin/plans'
    | '/mehla-admin/revenue'
    | '/mehla-admin/roles'
    | '/mehla-admin/security'
    | '/mehla-admin/seo'
    | '/mehla-admin/settings'
    | '/mehla-admin/sms'
    | '/mehla-admin/staff'
    | '/mehla-admin/subscriptions'
    | '/mehla-admin/support'
    | '/mehla-admin/users'
    | '/share/$token'
    | '/upload/$token'
    | '/mehla-admin/'
    | '/upload/'
    | '/cases/$id'
    | '/api/public/health'
    | '/cases/'
    | '/api/public/doc/$token'
    | '/api/public/hooks/cleanup-secure-artifacts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/pending-access'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/clients'
    | '/dashboard'
    | '/deadlines'
    | '/documents'
    | '/hearings'
    | '/print-log'
    | '/search'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/tasks'
    | '/team'
    | '/auth/callback'
    | '/auth/verified'
    | '/mehla-admin/email'
    | '/mehla-admin/failures'
    | '/mehla-admin/logs'
    | '/mehla-admin/monitoring'
    | '/mehla-admin/notifications'
    | '/mehla-admin/organizations'
    | '/mehla-admin/plans'
    | '/mehla-admin/revenue'
    | '/mehla-admin/roles'
    | '/mehla-admin/security'
    | '/mehla-admin/seo'
    | '/mehla-admin/settings'
    | '/mehla-admin/sms'
    | '/mehla-admin/staff'
    | '/mehla-admin/subscriptions'
    | '/mehla-admin/support'
    | '/mehla-admin/users'
    | '/share/$token'
    | '/upload/$token'
    | '/mehla-admin'
    | '/upload'
    | '/cases/$id'
    | '/api/public/health'
    | '/cases'
    | '/api/public/doc/$token'
    | '/api/public/hooks/cleanup-secure-artifacts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/mehla-admin'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/pending-access'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/deadlines'
    | '/_authenticated/documents'
    | '/_authenticated/hearings'
    | '/_authenticated/print-log'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/_authenticated/support'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/auth/callback'
    | '/auth/verified'
    | '/mehla-admin/email'
    | '/mehla-admin/failures'
    | '/mehla-admin/logs'
    | '/mehla-admin/monitoring'
    | '/mehla-admin/notifications'
    | '/mehla-admin/organizations'
    | '/mehla-admin/plans'
    | '/mehla-admin/revenue'
    | '/mehla-admin/roles'
    | '/mehla-admin/security'
    | '/mehla-admin/seo'
    | '/mehla-admin/settings'
    | '/mehla-admin/sms'
    | '/mehla-admin/staff'
    | '/mehla-admin/subscriptions'
    | '/mehla-admin/support'
    | '/mehla-admin/users'
    | '/share/$token'
    | '/upload/$token'
    | '/mehla-admin/'
    | '/upload/'
    | '/_authenticated/cases/$id'
    | '/api/public/health'
    | '/_authenticated/cases/'
    | '/api/public/doc/$token'
    | '/api/public/hooks/cleanup-secure-artifacts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MehlaAdminRouteRoute: typeof MehlaAdminRouteRouteWithChildren
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PendingAccessRoute: typeof PendingAccessRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
  ShareTokenRoute: typeof ShareTokenRoute
  UploadTokenRoute: typeof UploadTokenRoute
  UploadIndexRoute: typeof UploadIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicDocTokenRoute: typeof ApiPublicDocTokenRoute
  ApiPublicHooksCleanupSecureArtifactsRoute: typeof ApiPublicHooksCleanupSecureArtifactsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-access': {
      id: '/pending-access'
      path: '/pending-access'
      fullPath: '/pending-access'
      preLoaderRoute: typeof PendingAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehla-admin': {
      id: '/mehla-admin'
      path: '/mehla-admin'
      fullPath: '/mehla-admin'
      preLoaderRoute: typeof MehlaAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof UploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehla-admin/': {
      id: '/mehla-admin/'
      path: '/'
      fullPath: '/mehla-admin/'
      preLoaderRoute: typeof MehlaAdminIndexRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/upload/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehla-admin/users': {
      id: '/mehla-admin/users'
      path: '/users'
      fullPath: '/mehla-admin/users'
      preLoaderRoute: typeof MehlaAdminUsersRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/support': {
      id: '/mehla-admin/support'
      path: '/support'
      fullPath: '/mehla-admin/support'
      preLoaderRoute: typeof MehlaAdminSupportRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/subscriptions': {
      id: '/mehla-admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/mehla-admin/subscriptions'
      preLoaderRoute: typeof MehlaAdminSubscriptionsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/staff': {
      id: '/mehla-admin/staff'
      path: '/staff'
      fullPath: '/mehla-admin/staff'
      preLoaderRoute: typeof MehlaAdminStaffRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/sms': {
      id: '/mehla-admin/sms'
      path: '/sms'
      fullPath: '/mehla-admin/sms'
      preLoaderRoute: typeof MehlaAdminSmsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/settings': {
      id: '/mehla-admin/settings'
      path: '/settings'
      fullPath: '/mehla-admin/settings'
      preLoaderRoute: typeof MehlaAdminSettingsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/seo': {
      id: '/mehla-admin/seo'
      path: '/seo'
      fullPath: '/mehla-admin/seo'
      preLoaderRoute: typeof MehlaAdminSeoRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/security': {
      id: '/mehla-admin/security'
      path: '/security'
      fullPath: '/mehla-admin/security'
      preLoaderRoute: typeof MehlaAdminSecurityRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/roles': {
      id: '/mehla-admin/roles'
      path: '/roles'
      fullPath: '/mehla-admin/roles'
      preLoaderRoute: typeof MehlaAdminRolesRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/revenue': {
      id: '/mehla-admin/revenue'
      path: '/revenue'
      fullPath: '/mehla-admin/revenue'
      preLoaderRoute: typeof MehlaAdminRevenueRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/plans': {
      id: '/mehla-admin/plans'
      path: '/plans'
      fullPath: '/mehla-admin/plans'
      preLoaderRoute: typeof MehlaAdminPlansRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/organizations': {
      id: '/mehla-admin/organizations'
      path: '/organizations'
      fullPath: '/mehla-admin/organizations'
      preLoaderRoute: typeof MehlaAdminOrganizationsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/notifications': {
      id: '/mehla-admin/notifications'
      path: '/notifications'
      fullPath: '/mehla-admin/notifications'
      preLoaderRoute: typeof MehlaAdminNotificationsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/monitoring': {
      id: '/mehla-admin/monitoring'
      path: '/monitoring'
      fullPath: '/mehla-admin/monitoring'
      preLoaderRoute: typeof MehlaAdminMonitoringRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/logs': {
      id: '/mehla-admin/logs'
      path: '/logs'
      fullPath: '/mehla-admin/logs'
      preLoaderRoute: typeof MehlaAdminLogsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/failures': {
      id: '/mehla-admin/failures'
      path: '/failures'
      fullPath: '/mehla-admin/failures'
      preLoaderRoute: typeof MehlaAdminFailuresRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/email': {
      id: '/mehla-admin/email'
      path: '/email'
      fullPath: '/mehla-admin/email'
      preLoaderRoute: typeof MehlaAdminEmailRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/auth/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print-log': {
      id: '/_authenticated/print-log'
      path: '/print-log'
      fullPath: '/print-log'
      preLoaderRoute: typeof AuthenticatedPrintLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hearings': {
      id: '/_authenticated/hearings'
      path: '/hearings'
      fullPath: '/hearings'
      preLoaderRoute: typeof AuthenticatedHearingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deadlines': {
      id: '/_authenticated/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof AuthenticatedDeadlinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cases/$id': {
      id: '/_authenticated/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof AuthenticatedCasesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/cleanup-secure-artifacts': {
      id: '/api/public/hooks/cleanup-secure-artifacts'
      path: '/api/public/hooks/cleanup-secure-artifacts'
      fullPath: '/api/public/hooks/cleanup-secure-artifacts'
      preLoaderRoute: typeof ApiPublicHooksCleanupSecureArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/doc/$token': {
      id: '/api/public/doc/$token'
      path: '/api/public/doc/$token'
      fullPath: '/api/public/doc/$token'
      preLoaderRoute: typeof ApiPublicDocTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeadlinesRoute: typeof AuthenticatedDeadlinesRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedHearingsRoute: typeof AuthenticatedHearingsRoute
  AuthenticatedPrintLogRoute: typeof AuthenticatedPrintLogRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedCasesIdRoute: typeof AuthenticatedCasesIdRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeadlinesRoute: AuthenticatedDeadlinesRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedHearingsRoute: AuthenticatedHearingsRoute,
  AuthenticatedPrintLogRoute: AuthenticatedPrintLogRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedCasesIdRoute: AuthenticatedCasesIdRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MehlaAdminRouteRouteChildren {
  MehlaAdminEmailRoute: typeof MehlaAdminEmailRoute
  MehlaAdminFailuresRoute: typeof MehlaAdminFailuresRoute
  MehlaAdminLogsRoute: typeof MehlaAdminLogsRoute
  MehlaAdminMonitoringRoute: typeof MehlaAdminMonitoringRoute
  MehlaAdminNotificationsRoute: typeof MehlaAdminNotificationsRoute
  MehlaAdminOrganizationsRoute: typeof MehlaAdminOrganizationsRoute
  MehlaAdminPlansRoute: typeof MehlaAdminPlansRoute
  MehlaAdminRevenueRoute: typeof MehlaAdminRevenueRoute
  MehlaAdminRolesRoute: typeof MehlaAdminRolesRoute
  MehlaAdminSecurityRoute: typeof MehlaAdminSecurityRoute
  MehlaAdminSeoRoute: typeof MehlaAdminSeoRoute
  MehlaAdminSettingsRoute: typeof MehlaAdminSettingsRoute
  MehlaAdminSmsRoute: typeof MehlaAdminSmsRoute
  MehlaAdminStaffRoute: typeof MehlaAdminStaffRoute
  MehlaAdminSubscriptionsRoute: typeof MehlaAdminSubscriptionsRoute
  MehlaAdminSupportRoute: typeof MehlaAdminSupportRoute
  MehlaAdminUsersRoute: typeof MehlaAdminUsersRoute
  MehlaAdminIndexRoute: typeof MehlaAdminIndexRoute
}

const MehlaAdminRouteRouteChildren: MehlaAdminRouteRouteChildren = {
  MehlaAdminEmailRoute: MehlaAdminEmailRoute,
  MehlaAdminFailuresRoute: MehlaAdminFailuresRoute,
  MehlaAdminLogsRoute: MehlaAdminLogsRoute,
  MehlaAdminMonitoringRoute: MehlaAdminMonitoringRoute,
  MehlaAdminNotificationsRoute: MehlaAdminNotificationsRoute,
  MehlaAdminOrganizationsRoute: MehlaAdminOrganizationsRoute,
  MehlaAdminPlansRoute: MehlaAdminPlansRoute,
  MehlaAdminRevenueRoute: MehlaAdminRevenueRoute,
  MehlaAdminRolesRoute: MehlaAdminRolesRoute,
  MehlaAdminSecurityRoute: MehlaAdminSecurityRoute,
  MehlaAdminSeoRoute: MehlaAdminSeoRoute,
  MehlaAdminSettingsRoute: MehlaAdminSettingsRoute,
  MehlaAdminSmsRoute: MehlaAdminSmsRoute,
  MehlaAdminStaffRoute: MehlaAdminStaffRoute,
  MehlaAdminSubscriptionsRoute: MehlaAdminSubscriptionsRoute,
  MehlaAdminSupportRoute: MehlaAdminSupportRoute,
  MehlaAdminUsersRoute: MehlaAdminUsersRoute,
  MehlaAdminIndexRoute: MehlaAdminIndexRoute,
}

const MehlaAdminRouteRouteWithChildren = MehlaAdminRouteRoute._addFileChildren(
  MehlaAdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MehlaAdminRouteRoute: MehlaAdminRouteRouteWithChildren,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PendingAccessRoute: PendingAccessRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
  ShareTokenRoute: ShareTokenRoute,
  UploadTokenRoute: UploadTokenRoute,
  UploadIndexRoute: UploadIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicDocTokenRoute: ApiPublicDocTokenRoute,
  ApiPublicHooksCleanupSecureArtifactsRoute:
    ApiPublicHooksCleanupSecureArtifactsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
