/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PendingAccessRouteImport } from './routes/pending-access'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MehlaAdminRouteRouteImport } from './routes/mehla-admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadIndexRouteImport } from './routes/upload.index'
import { Route as MehlaAdminIndexRouteImport } from './routes/mehla-admin/index'
import { Route as UploadTokenRouteImport } from './routes/upload.$token'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as PortalSlugRouteImport } from './routes/portal.$slug'
import { Route as OfficeSlugRouteImport } from './routes/office.$slug'
import { Route as MehlaAdminUsersRouteImport } from './routes/mehla-admin/users'
import { Route as MehlaAdminSupportRouteImport } from './routes/mehla-admin/support'
import { Route as MehlaAdminSubscriptionsRouteImport } from './routes/mehla-admin/subscriptions'
import { Route as MehlaAdminStaffRouteImport } from './routes/mehla-admin/staff'
import { Route as MehlaAdminSmsRouteImport } from './routes/mehla-admin/sms'
import { Route as MehlaAdminSettingsRouteImport } from './routes/mehla-admin/settings'
import { Route as MehlaAdminServicesRouteImport } from './routes/mehla-admin/services'
import { Route as MehlaAdminSeoRouteImport } from './routes/mehla-admin/seo'
import { Route as MehlaAdminSecurityRouteImport } from './routes/mehla-admin/security'
import { Route as MehlaAdminRolesRouteImport } from './routes/mehla-admin/roles'
import { Route as MehlaAdminRevenueRouteImport } from './routes/mehla-admin/revenue'
import { Route as MehlaAdminRbacRouteImport } from './routes/mehla-admin/rbac'
import { Route as MehlaAdminProvidersRouteImport } from './routes/mehla-admin/providers'
import { Route as MehlaAdminPlansRouteImport } from './routes/mehla-admin/plans'
import { Route as MehlaAdminOrganizationsRouteImport } from './routes/mehla-admin/organizations'
import { Route as MehlaAdminNotificationsRouteImport } from './routes/mehla-admin/notifications'
import { Route as MehlaAdminMonitoringRouteImport } from './routes/mehla-admin/monitoring'
import { Route as MehlaAdminMarketingRouteImport } from './routes/mehla-admin/marketing'
import { Route as MehlaAdminMailRouteImport } from './routes/mehla-admin/mail'
import { Route as MehlaAdminLogsRouteImport } from './routes/mehla-admin/logs'
import { Route as MehlaAdminJobsRouteImport } from './routes/mehla-admin/jobs'
import { Route as MehlaAdminIntegrationsRouteImport } from './routes/mehla-admin/integrations'
import { Route as MehlaAdminHrRouteImport } from './routes/mehla-admin/hr'
import { Route as MehlaAdminFlagsRouteImport } from './routes/mehla-admin/flags'
import { Route as MehlaAdminFailuresRouteImport } from './routes/mehla-admin/failures'
import { Route as MehlaAdminEmailRouteImport } from './routes/mehla-admin/email'
import { Route as MehlaAdminDesignRouteImport } from './routes/mehla-admin/design'
import { Route as MehlaAdminCrmRouteImport } from './routes/mehla-admin/crm'
import { Route as MehlaAdminContentRouteImport } from './routes/mehla-admin/content'
import { Route as MehlaAdminBackupsRouteImport } from './routes/mehla-admin/backups'
import { Route as MehlaAdminAnalyticsRouteImport } from './routes/mehla-admin/analytics'
import { Route as MehlaAdminActivityRouteImport } from './routes/mehla-admin/activity'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthVerifiedRouteImport } from './routes/auth.verified'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'
import { Route as AuthenticatedTeamPerformanceRouteImport } from './routes/_authenticated/team-performance'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedPrintLogRouteImport } from './routes/_authenticated/print-log'
import { Route as AuthenticatedOfficePageRouteImport } from './routes/_authenticated/office-page'
import { Route as AuthenticatedHearingsRouteImport } from './routes/_authenticated/hearings'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDeadlinesRouteImport } from './routes/_authenticated/deadlines'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBayanRouteImport } from './routes/_authenticated/bayan'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as MehlaAdminSalesIndexRouteImport } from './routes/mehla-admin/sales/index'
import { Route as MehlaAdminBillingIndexRouteImport } from './routes/mehla-admin/billing/index'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated/cases.index'
import { Route as MehlaAdminSupportTicketIdRouteImport } from './routes/mehla-admin/support/$ticketId'
import { Route as MehlaAdminSalesIdRouteImport } from './routes/mehla-admin/sales/$id'
import { Route as MehlaAdminBillingIdRouteImport } from './routes/mehla-admin/billing/$id'
import { Route as ApiPublicWebhookRouteImport } from './routes/api/public/webhook'
import { Route as ApiPublicThemeDotcssRouteImport } from './routes/api/public/theme[.]css'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiAiBayanChatRouteImport } from './routes/api/ai/bayan-chat'
import { Route as AuthenticatedTeamPerformanceMemberIdRouteImport } from './routes/_authenticated/team-performance.$memberId'
import { Route as AuthenticatedCasesIdRouteImport } from './routes/_authenticated/cases.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWhSlugRouteImport } from './routes/api/public/wh.$slug'
import { Route as ApiPublicWebhooksSlugRouteImport } from './routes/api/public/webhooks/$slug'
import { Route as ApiPublicPaymentsProviderRouteImport } from './routes/api/public/payments/$provider'
import { Route as ApiPublicOfficeLeadRouteImport } from './routes/api/public/office/lead'
import { Route as ApiPublicOfficeEventRouteImport } from './routes/api/public/office/event'
import { Route as ApiPublicHooksOperationalScoreRouteImport } from './routes/api/public/hooks/operational-score'
import { Route as ApiPublicHooksOperationalRemindersRouteImport } from './routes/api/public/hooks/operational-reminders'
import { Route as ApiPublicHooksNotificationsDispatchRouteImport } from './routes/api/public/hooks/notifications-dispatch'
import { Route as ApiPublicHooksNotificationEmailsRouteImport } from './routes/api/public/hooks/notification-emails'
import { Route as ApiPublicHooksMailSyncRouteImport } from './routes/api/public/hooks/mail-sync'
import { Route as ApiPublicHooksEmailInboundRouteImport } from './routes/api/public/hooks/email-inbound'
import { Route as ApiPublicHooksEmailDispatchRouteImport } from './routes/api/public/hooks/email-dispatch'
import { Route as ApiPublicHooksCleanupSecureArtifactsRouteImport } from './routes/api/public/hooks/cleanup-secure-artifacts'
import { Route as ApiPublicDocTokenRouteImport } from './routes/api/public/doc.$token'
import { Route as ApiIntegrationsOnedriveCallbackRouteImport } from './routes/api/integrations/onedrive/callback'
import { Route as ApiPublicOfficeMediaSplatRouteImport } from './routes/api/public/office/media/$'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingAccessRoute = PendingAccessRouteImport.update({
  id: '/pending-access',
  path: '/pending-access',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MehlaAdminRouteRoute = MehlaAdminRouteRouteImport.update({
  id: '/mehla-admin',
  path: '/mehla-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadIndexRoute = UploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const MehlaAdminIndexRoute = MehlaAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeSlugRoute = OfficeSlugRouteImport.update({
  id: '/office/$slug',
  path: '/office/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MehlaAdminUsersRoute = MehlaAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSupportRoute = MehlaAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSubscriptionsRoute = MehlaAdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminStaffRoute = MehlaAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSmsRoute = MehlaAdminSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSettingsRoute = MehlaAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminServicesRoute = MehlaAdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSeoRoute = MehlaAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminSecurityRoute = MehlaAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminRolesRoute = MehlaAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminRevenueRoute = MehlaAdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminRbacRoute = MehlaAdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminProvidersRoute = MehlaAdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminPlansRoute = MehlaAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminOrganizationsRoute = MehlaAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminNotificationsRoute = MehlaAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminMonitoringRoute = MehlaAdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminMarketingRoute = MehlaAdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminMailRoute = MehlaAdminMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminLogsRoute = MehlaAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminJobsRoute = MehlaAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminIntegrationsRoute = MehlaAdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminHrRoute = MehlaAdminHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminFlagsRoute = MehlaAdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminFailuresRoute = MehlaAdminFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminEmailRoute = MehlaAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminDesignRoute = MehlaAdminDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminCrmRoute = MehlaAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminContentRoute = MehlaAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminBackupsRoute = MehlaAdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminAnalyticsRoute = MehlaAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminActivityRoute = MehlaAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/auth/verified',
  path: '/auth/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamPerformanceRoute =
  AuthenticatedTeamPerformanceRouteImport.update({
    id: '/team-performance',
    path: '/team-performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintLogRoute = AuthenticatedPrintLogRouteImport.update({
  id: '/print-log',
  path: '/print-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficePageRoute = AuthenticatedOfficePageRouteImport.update({
  id: '/office-page',
  path: '/office-page',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHearingsRoute = AuthenticatedHearingsRouteImport.update({
  id: '/hearings',
  path: '/hearings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeadlinesRoute = AuthenticatedDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBayanRoute = AuthenticatedBayanRouteImport.update({
  id: '/bayan',
  path: '/bayan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const MehlaAdminSalesIndexRoute = MehlaAdminSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminBillingIndexRoute = MehlaAdminBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MehlaAdminSupportTicketIdRoute =
  MehlaAdminSupportTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => MehlaAdminSupportRoute,
  } as any)
const MehlaAdminSalesIdRoute = MehlaAdminSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const MehlaAdminBillingIdRoute = MehlaAdminBillingIdRouteImport.update({
  id: '/billing/$id',
  path: '/billing/$id',
  getParentRoute: () => MehlaAdminRouteRoute,
} as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicThemeDotcssRoute = ApiPublicThemeDotcssRouteImport.update({
  id: '/api/public/theme.css',
  path: '/api/public/theme.css',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiBayanChatRoute = ApiAiBayanChatRouteImport.update({
  id: '/api/ai/bayan-chat',
  path: '/api/ai/bayan-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamPerformanceMemberIdRoute =
  AuthenticatedTeamPerformanceMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedTeamPerformanceRoute,
  } as any)
const AuthenticatedCasesIdRoute = AuthenticatedCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhSlugRoute = ApiPublicWhSlugRouteImport.update({
  id: '/api/public/wh/$slug',
  path: '/api/public/wh/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksSlugRoute = ApiPublicWebhooksSlugRouteImport.update({
  id: '/api/public/webhooks/$slug',
  path: '/api/public/webhooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsProviderRoute =
  ApiPublicPaymentsProviderRouteImport.update({
    id: '/api/public/payments/$provider',
    path: '/api/public/payments/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOfficeLeadRoute = ApiPublicOfficeLeadRouteImport.update({
  id: '/api/public/office/lead',
  path: '/api/public/office/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOfficeEventRoute = ApiPublicOfficeEventRouteImport.update({
  id: '/api/public/office/event',
  path: '/api/public/office/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksOperationalScoreRoute =
  ApiPublicHooksOperationalScoreRouteImport.update({
    id: '/api/public/hooks/operational-score',
    path: '/api/public/hooks/operational-score',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOperationalRemindersRoute =
  ApiPublicHooksOperationalRemindersRouteImport.update({
    id: '/api/public/hooks/operational-reminders',
    path: '/api/public/hooks/operational-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotificationsDispatchRoute =
  ApiPublicHooksNotificationsDispatchRouteImport.update({
    id: '/api/public/hooks/notifications-dispatch',
    path: '/api/public/hooks/notifications-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotificationEmailsRoute =
  ApiPublicHooksNotificationEmailsRouteImport.update({
    id: '/api/public/hooks/notification-emails',
    path: '/api/public/hooks/notification-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMailSyncRoute = ApiPublicHooksMailSyncRouteImport.update({
  id: '/api/public/hooks/mail-sync',
  path: '/api/public/hooks/mail-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEmailInboundRoute =
  ApiPublicHooksEmailInboundRouteImport.update({
    id: '/api/public/hooks/email-inbound',
    path: '/api/public/hooks/email-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailDispatchRoute =
  ApiPublicHooksEmailDispatchRouteImport.update({
    id: '/api/public/hooks/email-dispatch',
    path: '/api/public/hooks/email-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCleanupSecureArtifactsRoute =
  ApiPublicHooksCleanupSecureArtifactsRouteImport.update({
    id: '/api/public/hooks/cleanup-secure-artifacts',
    path: '/api/public/hooks/cleanup-secure-artifacts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDocTokenRoute = ApiPublicDocTokenRouteImport.update({
  id: '/api/public/doc/$token',
  path: '/api/public/doc/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsOnedriveCallbackRoute =
  ApiIntegrationsOnedriveCallbackRouteImport.update({
    id: '/api/integrations/onedrive/callback',
    path: '/api/integrations/onedrive/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOfficeMediaSplatRoute =
  ApiPublicOfficeMediaSplatRouteImport.update({
    id: '/api/public/office/media/$',
    path: '/api/public/office/media/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mehla-admin': typeof MehlaAdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-access': typeof PendingAccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/bayan': typeof AuthenticatedBayanRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/hearings': typeof AuthenticatedHearingsRoute
  '/office-page': typeof AuthenticatedOfficePageRoute
  '/print-log': typeof AuthenticatedPrintLogRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/team-performance': typeof AuthenticatedTeamPerformanceRouteWithChildren
  '/api/webhook': typeof ApiWebhookRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mehla-admin/activity': typeof MehlaAdminActivityRoute
  '/mehla-admin/analytics': typeof MehlaAdminAnalyticsRoute
  '/mehla-admin/backups': typeof MehlaAdminBackupsRoute
  '/mehla-admin/content': typeof MehlaAdminContentRoute
  '/mehla-admin/crm': typeof MehlaAdminCrmRoute
  '/mehla-admin/design': typeof MehlaAdminDesignRoute
  '/mehla-admin/email': typeof MehlaAdminEmailRoute
  '/mehla-admin/failures': typeof MehlaAdminFailuresRoute
  '/mehla-admin/flags': typeof MehlaAdminFlagsRoute
  '/mehla-admin/hr': typeof MehlaAdminHrRoute
  '/mehla-admin/integrations': typeof MehlaAdminIntegrationsRoute
  '/mehla-admin/jobs': typeof MehlaAdminJobsRoute
  '/mehla-admin/logs': typeof MehlaAdminLogsRoute
  '/mehla-admin/mail': typeof MehlaAdminMailRoute
  '/mehla-admin/marketing': typeof MehlaAdminMarketingRoute
  '/mehla-admin/monitoring': typeof MehlaAdminMonitoringRoute
  '/mehla-admin/notifications': typeof MehlaAdminNotificationsRoute
  '/mehla-admin/organizations': typeof MehlaAdminOrganizationsRoute
  '/mehla-admin/plans': typeof MehlaAdminPlansRoute
  '/mehla-admin/providers': typeof MehlaAdminProvidersRoute
  '/mehla-admin/rbac': typeof MehlaAdminRbacRoute
  '/mehla-admin/revenue': typeof MehlaAdminRevenueRoute
  '/mehla-admin/roles': typeof MehlaAdminRolesRoute
  '/mehla-admin/security': typeof MehlaAdminSecurityRoute
  '/mehla-admin/seo': typeof MehlaAdminSeoRoute
  '/mehla-admin/services': typeof MehlaAdminServicesRoute
  '/mehla-admin/settings': typeof MehlaAdminSettingsRoute
  '/mehla-admin/sms': typeof MehlaAdminSmsRoute
  '/mehla-admin/staff': typeof MehlaAdminStaffRoute
  '/mehla-admin/subscriptions': typeof MehlaAdminSubscriptionsRoute
  '/mehla-admin/support': typeof MehlaAdminSupportRouteWithChildren
  '/mehla-admin/users': typeof MehlaAdminUsersRoute
  '/office/$slug': typeof OfficeSlugRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/mehla-admin/': typeof MehlaAdminIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/cases/$id': typeof AuthenticatedCasesIdRoute
  '/team-performance/$memberId': typeof AuthenticatedTeamPerformanceMemberIdRoute
  '/api/ai/bayan-chat': typeof ApiAiBayanChatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/theme.css': typeof ApiPublicThemeDotcssRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/mehla-admin/billing/$id': typeof MehlaAdminBillingIdRoute
  '/mehla-admin/sales/$id': typeof MehlaAdminSalesIdRoute
  '/mehla-admin/support/$ticketId': typeof MehlaAdminSupportTicketIdRoute
  '/cases/': typeof AuthenticatedCasesIndexRoute
  '/mehla-admin/billing/': typeof MehlaAdminBillingIndexRoute
  '/mehla-admin/sales/': typeof MehlaAdminSalesIndexRoute
  '/api/integrations/onedrive/callback': typeof ApiIntegrationsOnedriveCallbackRoute
  '/api/public/doc/$token': typeof ApiPublicDocTokenRoute
  '/api/public/hooks/cleanup-secure-artifacts': typeof ApiPublicHooksCleanupSecureArtifactsRoute
  '/api/public/hooks/email-dispatch': typeof ApiPublicHooksEmailDispatchRoute
  '/api/public/hooks/email-inbound': typeof ApiPublicHooksEmailInboundRoute
  '/api/public/hooks/mail-sync': typeof ApiPublicHooksMailSyncRoute
  '/api/public/hooks/notification-emails': typeof ApiPublicHooksNotificationEmailsRoute
  '/api/public/hooks/notifications-dispatch': typeof ApiPublicHooksNotificationsDispatchRoute
  '/api/public/hooks/operational-reminders': typeof ApiPublicHooksOperationalRemindersRoute
  '/api/public/hooks/operational-score': typeof ApiPublicHooksOperationalScoreRoute
  '/api/public/office/event': typeof ApiPublicOfficeEventRoute
  '/api/public/office/lead': typeof ApiPublicOfficeLeadRoute
  '/api/public/payments/$provider': typeof ApiPublicPaymentsProviderRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
  '/api/public/wh/$slug': typeof ApiPublicWhSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/api/public/office/media/$': typeof ApiPublicOfficeMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-access': typeof PendingAccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/bayan': typeof AuthenticatedBayanRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/hearings': typeof AuthenticatedHearingsRoute
  '/office-page': typeof AuthenticatedOfficePageRoute
  '/print-log': typeof AuthenticatedPrintLogRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/team-performance': typeof AuthenticatedTeamPerformanceRouteWithChildren
  '/api/webhook': typeof ApiWebhookRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mehla-admin/activity': typeof MehlaAdminActivityRoute
  '/mehla-admin/analytics': typeof MehlaAdminAnalyticsRoute
  '/mehla-admin/backups': typeof MehlaAdminBackupsRoute
  '/mehla-admin/content': typeof MehlaAdminContentRoute
  '/mehla-admin/crm': typeof MehlaAdminCrmRoute
  '/mehla-admin/design': typeof MehlaAdminDesignRoute
  '/mehla-admin/email': typeof MehlaAdminEmailRoute
  '/mehla-admin/failures': typeof MehlaAdminFailuresRoute
  '/mehla-admin/flags': typeof MehlaAdminFlagsRoute
  '/mehla-admin/hr': typeof MehlaAdminHrRoute
  '/mehla-admin/integrations': typeof MehlaAdminIntegrationsRoute
  '/mehla-admin/jobs': typeof MehlaAdminJobsRoute
  '/mehla-admin/logs': typeof MehlaAdminLogsRoute
  '/mehla-admin/mail': typeof MehlaAdminMailRoute
  '/mehla-admin/marketing': typeof MehlaAdminMarketingRoute
  '/mehla-admin/monitoring': typeof MehlaAdminMonitoringRoute
  '/mehla-admin/notifications': typeof MehlaAdminNotificationsRoute
  '/mehla-admin/organizations': typeof MehlaAdminOrganizationsRoute
  '/mehla-admin/plans': typeof MehlaAdminPlansRoute
  '/mehla-admin/providers': typeof MehlaAdminProvidersRoute
  '/mehla-admin/rbac': typeof MehlaAdminRbacRoute
  '/mehla-admin/revenue': typeof MehlaAdminRevenueRoute
  '/mehla-admin/roles': typeof MehlaAdminRolesRoute
  '/mehla-admin/security': typeof MehlaAdminSecurityRoute
  '/mehla-admin/seo': typeof MehlaAdminSeoRoute
  '/mehla-admin/services': typeof MehlaAdminServicesRoute
  '/mehla-admin/settings': typeof MehlaAdminSettingsRoute
  '/mehla-admin/sms': typeof MehlaAdminSmsRoute
  '/mehla-admin/staff': typeof MehlaAdminStaffRoute
  '/mehla-admin/subscriptions': typeof MehlaAdminSubscriptionsRoute
  '/mehla-admin/support': typeof MehlaAdminSupportRouteWithChildren
  '/mehla-admin/users': typeof MehlaAdminUsersRoute
  '/office/$slug': typeof OfficeSlugRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/mehla-admin': typeof MehlaAdminIndexRoute
  '/upload': typeof UploadIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/cases/$id': typeof AuthenticatedCasesIdRoute
  '/team-performance/$memberId': typeof AuthenticatedTeamPerformanceMemberIdRoute
  '/api/ai/bayan-chat': typeof ApiAiBayanChatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/theme.css': typeof ApiPublicThemeDotcssRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/mehla-admin/billing/$id': typeof MehlaAdminBillingIdRoute
  '/mehla-admin/sales/$id': typeof MehlaAdminSalesIdRoute
  '/mehla-admin/support/$ticketId': typeof MehlaAdminSupportTicketIdRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/mehla-admin/billing': typeof MehlaAdminBillingIndexRoute
  '/mehla-admin/sales': typeof MehlaAdminSalesIndexRoute
  '/api/integrations/onedrive/callback': typeof ApiIntegrationsOnedriveCallbackRoute
  '/api/public/doc/$token': typeof ApiPublicDocTokenRoute
  '/api/public/hooks/cleanup-secure-artifacts': typeof ApiPublicHooksCleanupSecureArtifactsRoute
  '/api/public/hooks/email-dispatch': typeof ApiPublicHooksEmailDispatchRoute
  '/api/public/hooks/email-inbound': typeof ApiPublicHooksEmailInboundRoute
  '/api/public/hooks/mail-sync': typeof ApiPublicHooksMailSyncRoute
  '/api/public/hooks/notification-emails': typeof ApiPublicHooksNotificationEmailsRoute
  '/api/public/hooks/notifications-dispatch': typeof ApiPublicHooksNotificationsDispatchRoute
  '/api/public/hooks/operational-reminders': typeof ApiPublicHooksOperationalRemindersRoute
  '/api/public/hooks/operational-score': typeof ApiPublicHooksOperationalScoreRoute
  '/api/public/office/event': typeof ApiPublicOfficeEventRoute
  '/api/public/office/lead': typeof ApiPublicOfficeLeadRoute
  '/api/public/payments/$provider': typeof ApiPublicPaymentsProviderRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
  '/api/public/wh/$slug': typeof ApiPublicWhSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/api/public/office/media/$': typeof ApiPublicOfficeMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/mehla-admin': typeof MehlaAdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-access': typeof PendingAccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/bayan': typeof AuthenticatedBayanRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deadlines': typeof AuthenticatedDeadlinesRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/hearings': typeof AuthenticatedHearingsRoute
  '/_authenticated/office-page': typeof AuthenticatedOfficePageRoute
  '/_authenticated/print-log': typeof AuthenticatedPrintLogRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/team-performance': typeof AuthenticatedTeamPerformanceRouteWithChildren
  '/api/webhook': typeof ApiWebhookRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mehla-admin/activity': typeof MehlaAdminActivityRoute
  '/mehla-admin/analytics': typeof MehlaAdminAnalyticsRoute
  '/mehla-admin/backups': typeof MehlaAdminBackupsRoute
  '/mehla-admin/content': typeof MehlaAdminContentRoute
  '/mehla-admin/crm': typeof MehlaAdminCrmRoute
  '/mehla-admin/design': typeof MehlaAdminDesignRoute
  '/mehla-admin/email': typeof MehlaAdminEmailRoute
  '/mehla-admin/failures': typeof MehlaAdminFailuresRoute
  '/mehla-admin/flags': typeof MehlaAdminFlagsRoute
  '/mehla-admin/hr': typeof MehlaAdminHrRoute
  '/mehla-admin/integrations': typeof MehlaAdminIntegrationsRoute
  '/mehla-admin/jobs': typeof MehlaAdminJobsRoute
  '/mehla-admin/logs': typeof MehlaAdminLogsRoute
  '/mehla-admin/mail': typeof MehlaAdminMailRoute
  '/mehla-admin/marketing': typeof MehlaAdminMarketingRoute
  '/mehla-admin/monitoring': typeof MehlaAdminMonitoringRoute
  '/mehla-admin/notifications': typeof MehlaAdminNotificationsRoute
  '/mehla-admin/organizations': typeof MehlaAdminOrganizationsRoute
  '/mehla-admin/plans': typeof MehlaAdminPlansRoute
  '/mehla-admin/providers': typeof MehlaAdminProvidersRoute
  '/mehla-admin/rbac': typeof MehlaAdminRbacRoute
  '/mehla-admin/revenue': typeof MehlaAdminRevenueRoute
  '/mehla-admin/roles': typeof MehlaAdminRolesRoute
  '/mehla-admin/security': typeof MehlaAdminSecurityRoute
  '/mehla-admin/seo': typeof MehlaAdminSeoRoute
  '/mehla-admin/services': typeof MehlaAdminServicesRoute
  '/mehla-admin/settings': typeof MehlaAdminSettingsRoute
  '/mehla-admin/sms': typeof MehlaAdminSmsRoute
  '/mehla-admin/staff': typeof MehlaAdminStaffRoute
  '/mehla-admin/subscriptions': typeof MehlaAdminSubscriptionsRoute
  '/mehla-admin/support': typeof MehlaAdminSupportRouteWithChildren
  '/mehla-admin/users': typeof MehlaAdminUsersRoute
  '/office/$slug': typeof OfficeSlugRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/mehla-admin/': typeof MehlaAdminIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/cases/$id': typeof AuthenticatedCasesIdRoute
  '/_authenticated/team-performance/$memberId': typeof AuthenticatedTeamPerformanceMemberIdRoute
  '/api/ai/bayan-chat': typeof ApiAiBayanChatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/theme.css': typeof ApiPublicThemeDotcssRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/mehla-admin/billing/$id': typeof MehlaAdminBillingIdRoute
  '/mehla-admin/sales/$id': typeof MehlaAdminSalesIdRoute
  '/mehla-admin/support/$ticketId': typeof MehlaAdminSupportTicketIdRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
  '/mehla-admin/billing/': typeof MehlaAdminBillingIndexRoute
  '/mehla-admin/sales/': typeof MehlaAdminSalesIndexRoute
  '/api/integrations/onedrive/callback': typeof ApiIntegrationsOnedriveCallbackRoute
  '/api/public/doc/$token': typeof ApiPublicDocTokenRoute
  '/api/public/hooks/cleanup-secure-artifacts': typeof ApiPublicHooksCleanupSecureArtifactsRoute
  '/api/public/hooks/email-dispatch': typeof ApiPublicHooksEmailDispatchRoute
  '/api/public/hooks/email-inbound': typeof ApiPublicHooksEmailInboundRoute
  '/api/public/hooks/mail-sync': typeof ApiPublicHooksMailSyncRoute
  '/api/public/hooks/notification-emails': typeof ApiPublicHooksNotificationEmailsRoute
  '/api/public/hooks/notifications-dispatch': typeof ApiPublicHooksNotificationsDispatchRoute
  '/api/public/hooks/operational-reminders': typeof ApiPublicHooksOperationalRemindersRoute
  '/api/public/hooks/operational-score': typeof ApiPublicHooksOperationalScoreRoute
  '/api/public/office/event': typeof ApiPublicOfficeEventRoute
  '/api/public/office/lead': typeof ApiPublicOfficeLeadRoute
  '/api/public/payments/$provider': typeof ApiPublicPaymentsProviderRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
  '/api/public/wh/$slug': typeof ApiPublicWhSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/api/public/office/media/$': typeof ApiPublicOfficeMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mehla-admin'
    | '/about'
    | '/contact'
    | '/docs'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/pending-access'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/bayan'
    | '/clients'
    | '/contracts'
    | '/dashboard'
    | '/deadlines'
    | '/documents'
    | '/hearings'
    | '/office-page'
    | '/print-log'
    | '/search'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/tasks'
    | '/team'
    | '/team-performance'
    | '/api/webhook'
    | '/auth/callback'
    | '/auth/verified'
    | '/invite/$token'
    | '/mehla-admin/activity'
    | '/mehla-admin/analytics'
    | '/mehla-admin/backups'
    | '/mehla-admin/content'
    | '/mehla-admin/crm'
    | '/mehla-admin/design'
    | '/mehla-admin/email'
    | '/mehla-admin/failures'
    | '/mehla-admin/flags'
    | '/mehla-admin/hr'
    | '/mehla-admin/integrations'
    | '/mehla-admin/jobs'
    | '/mehla-admin/logs'
    | '/mehla-admin/mail'
    | '/mehla-admin/marketing'
    | '/mehla-admin/monitoring'
    | '/mehla-admin/notifications'
    | '/mehla-admin/organizations'
    | '/mehla-admin/plans'
    | '/mehla-admin/providers'
    | '/mehla-admin/rbac'
    | '/mehla-admin/revenue'
    | '/mehla-admin/roles'
    | '/mehla-admin/security'
    | '/mehla-admin/seo'
    | '/mehla-admin/services'
    | '/mehla-admin/settings'
    | '/mehla-admin/sms'
    | '/mehla-admin/staff'
    | '/mehla-admin/subscriptions'
    | '/mehla-admin/support'
    | '/mehla-admin/users'
    | '/office/$slug'
    | '/portal/$slug'
    | '/share/$token'
    | '/sign/$token'
    | '/upload/$token'
    | '/mehla-admin/'
    | '/upload/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/cases/$id'
    | '/team-performance/$memberId'
    | '/api/ai/bayan-chat'
    | '/api/public/health'
    | '/api/public/theme.css'
    | '/api/public/webhook'
    | '/mehla-admin/billing/$id'
    | '/mehla-admin/sales/$id'
    | '/mehla-admin/support/$ticketId'
    | '/cases/'
    | '/mehla-admin/billing/'
    | '/mehla-admin/sales/'
    | '/api/integrations/onedrive/callback'
    | '/api/public/doc/$token'
    | '/api/public/hooks/cleanup-secure-artifacts'
    | '/api/public/hooks/email-dispatch'
    | '/api/public/hooks/email-inbound'
    | '/api/public/hooks/mail-sync'
    | '/api/public/hooks/notification-emails'
    | '/api/public/hooks/notifications-dispatch'
    | '/api/public/hooks/operational-reminders'
    | '/api/public/hooks/operational-score'
    | '/api/public/office/event'
    | '/api/public/office/lead'
    | '/api/public/payments/$provider'
    | '/api/public/webhooks/$slug'
    | '/api/public/wh/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/api/public/office/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/docs'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/pending-access'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/bayan'
    | '/clients'
    | '/contracts'
    | '/dashboard'
    | '/deadlines'
    | '/documents'
    | '/hearings'
    | '/office-page'
    | '/print-log'
    | '/search'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/tasks'
    | '/team'
    | '/team-performance'
    | '/api/webhook'
    | '/auth/callback'
    | '/auth/verified'
    | '/invite/$token'
    | '/mehla-admin/activity'
    | '/mehla-admin/analytics'
    | '/mehla-admin/backups'
    | '/mehla-admin/content'
    | '/mehla-admin/crm'
    | '/mehla-admin/design'
    | '/mehla-admin/email'
    | '/mehla-admin/failures'
    | '/mehla-admin/flags'
    | '/mehla-admin/hr'
    | '/mehla-admin/integrations'
    | '/mehla-admin/jobs'
    | '/mehla-admin/logs'
    | '/mehla-admin/mail'
    | '/mehla-admin/marketing'
    | '/mehla-admin/monitoring'
    | '/mehla-admin/notifications'
    | '/mehla-admin/organizations'
    | '/mehla-admin/plans'
    | '/mehla-admin/providers'
    | '/mehla-admin/rbac'
    | '/mehla-admin/revenue'
    | '/mehla-admin/roles'
    | '/mehla-admin/security'
    | '/mehla-admin/seo'
    | '/mehla-admin/services'
    | '/mehla-admin/settings'
    | '/mehla-admin/sms'
    | '/mehla-admin/staff'
    | '/mehla-admin/subscriptions'
    | '/mehla-admin/support'
    | '/mehla-admin/users'
    | '/office/$slug'
    | '/portal/$slug'
    | '/share/$token'
    | '/sign/$token'
    | '/upload/$token'
    | '/mehla-admin'
    | '/upload'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/cases/$id'
    | '/team-performance/$memberId'
    | '/api/ai/bayan-chat'
    | '/api/public/health'
    | '/api/public/theme.css'
    | '/api/public/webhook'
    | '/mehla-admin/billing/$id'
    | '/mehla-admin/sales/$id'
    | '/mehla-admin/support/$ticketId'
    | '/cases'
    | '/mehla-admin/billing'
    | '/mehla-admin/sales'
    | '/api/integrations/onedrive/callback'
    | '/api/public/doc/$token'
    | '/api/public/hooks/cleanup-secure-artifacts'
    | '/api/public/hooks/email-dispatch'
    | '/api/public/hooks/email-inbound'
    | '/api/public/hooks/mail-sync'
    | '/api/public/hooks/notification-emails'
    | '/api/public/hooks/notifications-dispatch'
    | '/api/public/hooks/operational-reminders'
    | '/api/public/hooks/operational-score'
    | '/api/public/office/event'
    | '/api/public/office/lead'
    | '/api/public/payments/$provider'
    | '/api/public/webhooks/$slug'
    | '/api/public/wh/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/api/public/office/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/mehla-admin'
    | '/about'
    | '/contact'
    | '/docs'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/pending-access'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/bayan'
    | '/_authenticated/clients'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/deadlines'
    | '/_authenticated/documents'
    | '/_authenticated/hearings'
    | '/_authenticated/office-page'
    | '/_authenticated/print-log'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/_authenticated/support'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/_authenticated/team-performance'
    | '/api/webhook'
    | '/auth/callback'
    | '/auth/verified'
    | '/invite/$token'
    | '/mehla-admin/activity'
    | '/mehla-admin/analytics'
    | '/mehla-admin/backups'
    | '/mehla-admin/content'
    | '/mehla-admin/crm'
    | '/mehla-admin/design'
    | '/mehla-admin/email'
    | '/mehla-admin/failures'
    | '/mehla-admin/flags'
    | '/mehla-admin/hr'
    | '/mehla-admin/integrations'
    | '/mehla-admin/jobs'
    | '/mehla-admin/logs'
    | '/mehla-admin/mail'
    | '/mehla-admin/marketing'
    | '/mehla-admin/monitoring'
    | '/mehla-admin/notifications'
    | '/mehla-admin/organizations'
    | '/mehla-admin/plans'
    | '/mehla-admin/providers'
    | '/mehla-admin/rbac'
    | '/mehla-admin/revenue'
    | '/mehla-admin/roles'
    | '/mehla-admin/security'
    | '/mehla-admin/seo'
    | '/mehla-admin/services'
    | '/mehla-admin/settings'
    | '/mehla-admin/sms'
    | '/mehla-admin/staff'
    | '/mehla-admin/subscriptions'
    | '/mehla-admin/support'
    | '/mehla-admin/users'
    | '/office/$slug'
    | '/portal/$slug'
    | '/share/$token'
    | '/sign/$token'
    | '/upload/$token'
    | '/mehla-admin/'
    | '/upload/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/cases/$id'
    | '/_authenticated/team-performance/$memberId'
    | '/api/ai/bayan-chat'
    | '/api/public/health'
    | '/api/public/theme.css'
    | '/api/public/webhook'
    | '/mehla-admin/billing/$id'
    | '/mehla-admin/sales/$id'
    | '/mehla-admin/support/$ticketId'
    | '/_authenticated/cases/'
    | '/mehla-admin/billing/'
    | '/mehla-admin/sales/'
    | '/api/integrations/onedrive/callback'
    | '/api/public/doc/$token'
    | '/api/public/hooks/cleanup-secure-artifacts'
    | '/api/public/hooks/email-dispatch'
    | '/api/public/hooks/email-inbound'
    | '/api/public/hooks/mail-sync'
    | '/api/public/hooks/notification-emails'
    | '/api/public/hooks/notifications-dispatch'
    | '/api/public/hooks/operational-reminders'
    | '/api/public/hooks/operational-score'
    | '/api/public/office/event'
    | '/api/public/office/lead'
    | '/api/public/payments/$provider'
    | '/api/public/webhooks/$slug'
    | '/api/public/wh/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/api/public/office/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MehlaAdminRouteRoute: typeof MehlaAdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  PendingAccessRoute: typeof PendingAccessRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OfficeSlugRoute: typeof OfficeSlugRoute
  PortalSlugRoute: typeof PortalSlugRoute
  ShareTokenRoute: typeof ShareTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  UploadTokenRoute: typeof UploadTokenRoute
  UploadIndexRoute: typeof UploadIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAiBayanChatRoute: typeof ApiAiBayanChatRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicThemeDotcssRoute: typeof ApiPublicThemeDotcssRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
  ApiIntegrationsOnedriveCallbackRoute: typeof ApiIntegrationsOnedriveCallbackRoute
  ApiPublicDocTokenRoute: typeof ApiPublicDocTokenRoute
  ApiPublicHooksCleanupSecureArtifactsRoute: typeof ApiPublicHooksCleanupSecureArtifactsRoute
  ApiPublicHooksEmailDispatchRoute: typeof ApiPublicHooksEmailDispatchRoute
  ApiPublicHooksEmailInboundRoute: typeof ApiPublicHooksEmailInboundRoute
  ApiPublicHooksMailSyncRoute: typeof ApiPublicHooksMailSyncRoute
  ApiPublicHooksNotificationEmailsRoute: typeof ApiPublicHooksNotificationEmailsRoute
  ApiPublicHooksNotificationsDispatchRoute: typeof ApiPublicHooksNotificationsDispatchRoute
  ApiPublicHooksOperationalRemindersRoute: typeof ApiPublicHooksOperationalRemindersRoute
  ApiPublicHooksOperationalScoreRoute: typeof ApiPublicHooksOperationalScoreRoute
  ApiPublicOfficeEventRoute: typeof ApiPublicOfficeEventRoute
  ApiPublicOfficeLeadRoute: typeof ApiPublicOfficeLeadRoute
  ApiPublicPaymentsProviderRoute: typeof ApiPublicPaymentsProviderRoute
  ApiPublicWebhooksSlugRoute: typeof ApiPublicWebhooksSlugRoute
  ApiPublicWhSlugRoute: typeof ApiPublicWhSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  ApiPublicOfficeMediaSplatRoute: typeof ApiPublicOfficeMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-access': {
      id: '/pending-access'
      path: '/pending-access'
      fullPath: '/pending-access'
      preLoaderRoute: typeof PendingAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehla-admin': {
      id: '/mehla-admin'
      path: '/mehla-admin'
      fullPath: '/mehla-admin'
      preLoaderRoute: typeof MehlaAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof UploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehla-admin/': {
      id: '/mehla-admin/'
      path: '/'
      fullPath: '/mehla-admin/'
      preLoaderRoute: typeof MehlaAdminIndexRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/upload/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$slug': {
      id: '/portal/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/$slug': {
      id: '/office/$slug'
      path: '/office/$slug'
      fullPath: '/office/$slug'
      preLoaderRoute: typeof OfficeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehla-admin/users': {
      id: '/mehla-admin/users'
      path: '/users'
      fullPath: '/mehla-admin/users'
      preLoaderRoute: typeof MehlaAdminUsersRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/support': {
      id: '/mehla-admin/support'
      path: '/support'
      fullPath: '/mehla-admin/support'
      preLoaderRoute: typeof MehlaAdminSupportRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/subscriptions': {
      id: '/mehla-admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/mehla-admin/subscriptions'
      preLoaderRoute: typeof MehlaAdminSubscriptionsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/staff': {
      id: '/mehla-admin/staff'
      path: '/staff'
      fullPath: '/mehla-admin/staff'
      preLoaderRoute: typeof MehlaAdminStaffRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/sms': {
      id: '/mehla-admin/sms'
      path: '/sms'
      fullPath: '/mehla-admin/sms'
      preLoaderRoute: typeof MehlaAdminSmsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/settings': {
      id: '/mehla-admin/settings'
      path: '/settings'
      fullPath: '/mehla-admin/settings'
      preLoaderRoute: typeof MehlaAdminSettingsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/services': {
      id: '/mehla-admin/services'
      path: '/services'
      fullPath: '/mehla-admin/services'
      preLoaderRoute: typeof MehlaAdminServicesRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/seo': {
      id: '/mehla-admin/seo'
      path: '/seo'
      fullPath: '/mehla-admin/seo'
      preLoaderRoute: typeof MehlaAdminSeoRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/security': {
      id: '/mehla-admin/security'
      path: '/security'
      fullPath: '/mehla-admin/security'
      preLoaderRoute: typeof MehlaAdminSecurityRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/roles': {
      id: '/mehla-admin/roles'
      path: '/roles'
      fullPath: '/mehla-admin/roles'
      preLoaderRoute: typeof MehlaAdminRolesRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/revenue': {
      id: '/mehla-admin/revenue'
      path: '/revenue'
      fullPath: '/mehla-admin/revenue'
      preLoaderRoute: typeof MehlaAdminRevenueRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/rbac': {
      id: '/mehla-admin/rbac'
      path: '/rbac'
      fullPath: '/mehla-admin/rbac'
      preLoaderRoute: typeof MehlaAdminRbacRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/providers': {
      id: '/mehla-admin/providers'
      path: '/providers'
      fullPath: '/mehla-admin/providers'
      preLoaderRoute: typeof MehlaAdminProvidersRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/plans': {
      id: '/mehla-admin/plans'
      path: '/plans'
      fullPath: '/mehla-admin/plans'
      preLoaderRoute: typeof MehlaAdminPlansRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/organizations': {
      id: '/mehla-admin/organizations'
      path: '/organizations'
      fullPath: '/mehla-admin/organizations'
      preLoaderRoute: typeof MehlaAdminOrganizationsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/notifications': {
      id: '/mehla-admin/notifications'
      path: '/notifications'
      fullPath: '/mehla-admin/notifications'
      preLoaderRoute: typeof MehlaAdminNotificationsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/monitoring': {
      id: '/mehla-admin/monitoring'
      path: '/monitoring'
      fullPath: '/mehla-admin/monitoring'
      preLoaderRoute: typeof MehlaAdminMonitoringRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/marketing': {
      id: '/mehla-admin/marketing'
      path: '/marketing'
      fullPath: '/mehla-admin/marketing'
      preLoaderRoute: typeof MehlaAdminMarketingRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/mail': {
      id: '/mehla-admin/mail'
      path: '/mail'
      fullPath: '/mehla-admin/mail'
      preLoaderRoute: typeof MehlaAdminMailRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/logs': {
      id: '/mehla-admin/logs'
      path: '/logs'
      fullPath: '/mehla-admin/logs'
      preLoaderRoute: typeof MehlaAdminLogsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/jobs': {
      id: '/mehla-admin/jobs'
      path: '/jobs'
      fullPath: '/mehla-admin/jobs'
      preLoaderRoute: typeof MehlaAdminJobsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/integrations': {
      id: '/mehla-admin/integrations'
      path: '/integrations'
      fullPath: '/mehla-admin/integrations'
      preLoaderRoute: typeof MehlaAdminIntegrationsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/hr': {
      id: '/mehla-admin/hr'
      path: '/hr'
      fullPath: '/mehla-admin/hr'
      preLoaderRoute: typeof MehlaAdminHrRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/flags': {
      id: '/mehla-admin/flags'
      path: '/flags'
      fullPath: '/mehla-admin/flags'
      preLoaderRoute: typeof MehlaAdminFlagsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/failures': {
      id: '/mehla-admin/failures'
      path: '/failures'
      fullPath: '/mehla-admin/failures'
      preLoaderRoute: typeof MehlaAdminFailuresRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/email': {
      id: '/mehla-admin/email'
      path: '/email'
      fullPath: '/mehla-admin/email'
      preLoaderRoute: typeof MehlaAdminEmailRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/design': {
      id: '/mehla-admin/design'
      path: '/design'
      fullPath: '/mehla-admin/design'
      preLoaderRoute: typeof MehlaAdminDesignRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/crm': {
      id: '/mehla-admin/crm'
      path: '/crm'
      fullPath: '/mehla-admin/crm'
      preLoaderRoute: typeof MehlaAdminCrmRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/content': {
      id: '/mehla-admin/content'
      path: '/content'
      fullPath: '/mehla-admin/content'
      preLoaderRoute: typeof MehlaAdminContentRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/backups': {
      id: '/mehla-admin/backups'
      path: '/backups'
      fullPath: '/mehla-admin/backups'
      preLoaderRoute: typeof MehlaAdminBackupsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/analytics': {
      id: '/mehla-admin/analytics'
      path: '/analytics'
      fullPath: '/mehla-admin/analytics'
      preLoaderRoute: typeof MehlaAdminAnalyticsRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/activity': {
      id: '/mehla-admin/activity'
      path: '/activity'
      fullPath: '/mehla-admin/activity'
      preLoaderRoute: typeof MehlaAdminActivityRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/auth/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team-performance': {
      id: '/_authenticated/team-performance'
      path: '/team-performance'
      fullPath: '/team-performance'
      preLoaderRoute: typeof AuthenticatedTeamPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print-log': {
      id: '/_authenticated/print-log'
      path: '/print-log'
      fullPath: '/print-log'
      preLoaderRoute: typeof AuthenticatedPrintLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office-page': {
      id: '/_authenticated/office-page'
      path: '/office-page'
      fullPath: '/office-page'
      preLoaderRoute: typeof AuthenticatedOfficePageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hearings': {
      id: '/_authenticated/hearings'
      path: '/hearings'
      fullPath: '/hearings'
      preLoaderRoute: typeof AuthenticatedHearingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deadlines': {
      id: '/_authenticated/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof AuthenticatedDeadlinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bayan': {
      id: '/_authenticated/bayan'
      path: '/bayan'
      fullPath: '/bayan'
      preLoaderRoute: typeof AuthenticatedBayanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehla-admin/sales/': {
      id: '/mehla-admin/sales/'
      path: '/sales'
      fullPath: '/mehla-admin/sales/'
      preLoaderRoute: typeof MehlaAdminSalesIndexRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/billing/': {
      id: '/mehla-admin/billing/'
      path: '/billing'
      fullPath: '/mehla-admin/billing/'
      preLoaderRoute: typeof MehlaAdminBillingIndexRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/mehla-admin/support/$ticketId': {
      id: '/mehla-admin/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/mehla-admin/support/$ticketId'
      preLoaderRoute: typeof MehlaAdminSupportTicketIdRouteImport
      parentRoute: typeof MehlaAdminSupportRoute
    }
    '/mehla-admin/sales/$id': {
      id: '/mehla-admin/sales/$id'
      path: '/sales/$id'
      fullPath: '/mehla-admin/sales/$id'
      preLoaderRoute: typeof MehlaAdminSalesIdRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/mehla-admin/billing/$id': {
      id: '/mehla-admin/billing/$id'
      path: '/billing/$id'
      fullPath: '/mehla-admin/billing/$id'
      preLoaderRoute: typeof MehlaAdminBillingIdRouteImport
      parentRoute: typeof MehlaAdminRouteRoute
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/theme.css': {
      id: '/api/public/theme.css'
      path: '/api/public/theme.css'
      fullPath: '/api/public/theme.css'
      preLoaderRoute: typeof ApiPublicThemeDotcssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/bayan-chat': {
      id: '/api/ai/bayan-chat'
      path: '/api/ai/bayan-chat'
      fullPath: '/api/ai/bayan-chat'
      preLoaderRoute: typeof ApiAiBayanChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team-performance/$memberId': {
      id: '/_authenticated/team-performance/$memberId'
      path: '/$memberId'
      fullPath: '/team-performance/$memberId'
      preLoaderRoute: typeof AuthenticatedTeamPerformanceMemberIdRouteImport
      parentRoute: typeof AuthenticatedTeamPerformanceRoute
    }
    '/_authenticated/cases/$id': {
      id: '/_authenticated/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof AuthenticatedCasesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wh/$slug': {
      id: '/api/public/wh/$slug'
      path: '/api/public/wh/$slug'
      fullPath: '/api/public/wh/$slug'
      preLoaderRoute: typeof ApiPublicWhSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/$slug': {
      id: '/api/public/webhooks/$slug'
      path: '/api/public/webhooks/$slug'
      fullPath: '/api/public/webhooks/$slug'
      preLoaderRoute: typeof ApiPublicWebhooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/$provider': {
      id: '/api/public/payments/$provider'
      path: '/api/public/payments/$provider'
      fullPath: '/api/public/payments/$provider'
      preLoaderRoute: typeof ApiPublicPaymentsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/office/lead': {
      id: '/api/public/office/lead'
      path: '/api/public/office/lead'
      fullPath: '/api/public/office/lead'
      preLoaderRoute: typeof ApiPublicOfficeLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/office/event': {
      id: '/api/public/office/event'
      path: '/api/public/office/event'
      fullPath: '/api/public/office/event'
      preLoaderRoute: typeof ApiPublicOfficeEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/operational-score': {
      id: '/api/public/hooks/operational-score'
      path: '/api/public/hooks/operational-score'
      fullPath: '/api/public/hooks/operational-score'
      preLoaderRoute: typeof ApiPublicHooksOperationalScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/operational-reminders': {
      id: '/api/public/hooks/operational-reminders'
      path: '/api/public/hooks/operational-reminders'
      fullPath: '/api/public/hooks/operational-reminders'
      preLoaderRoute: typeof ApiPublicHooksOperationalRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notifications-dispatch': {
      id: '/api/public/hooks/notifications-dispatch'
      path: '/api/public/hooks/notifications-dispatch'
      fullPath: '/api/public/hooks/notifications-dispatch'
      preLoaderRoute: typeof ApiPublicHooksNotificationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notification-emails': {
      id: '/api/public/hooks/notification-emails'
      path: '/api/public/hooks/notification-emails'
      fullPath: '/api/public/hooks/notification-emails'
      preLoaderRoute: typeof ApiPublicHooksNotificationEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mail-sync': {
      id: '/api/public/hooks/mail-sync'
      path: '/api/public/hooks/mail-sync'
      fullPath: '/api/public/hooks/mail-sync'
      preLoaderRoute: typeof ApiPublicHooksMailSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-inbound': {
      id: '/api/public/hooks/email-inbound'
      path: '/api/public/hooks/email-inbound'
      fullPath: '/api/public/hooks/email-inbound'
      preLoaderRoute: typeof ApiPublicHooksEmailInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-dispatch': {
      id: '/api/public/hooks/email-dispatch'
      path: '/api/public/hooks/email-dispatch'
      fullPath: '/api/public/hooks/email-dispatch'
      preLoaderRoute: typeof ApiPublicHooksEmailDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-secure-artifacts': {
      id: '/api/public/hooks/cleanup-secure-artifacts'
      path: '/api/public/hooks/cleanup-secure-artifacts'
      fullPath: '/api/public/hooks/cleanup-secure-artifacts'
      preLoaderRoute: typeof ApiPublicHooksCleanupSecureArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/doc/$token': {
      id: '/api/public/doc/$token'
      path: '/api/public/doc/$token'
      fullPath: '/api/public/doc/$token'
      preLoaderRoute: typeof ApiPublicDocTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/onedrive/callback': {
      id: '/api/integrations/onedrive/callback'
      path: '/api/integrations/onedrive/callback'
      fullPath: '/api/integrations/onedrive/callback'
      preLoaderRoute: typeof ApiIntegrationsOnedriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/office/media/$': {
      id: '/api/public/office/media/$'
      path: '/api/public/office/media/$'
      fullPath: '/api/public/office/media/$'
      preLoaderRoute: typeof ApiPublicOfficeMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedTeamPerformanceRouteChildren {
  AuthenticatedTeamPerformanceMemberIdRoute: typeof AuthenticatedTeamPerformanceMemberIdRoute
}

const AuthenticatedTeamPerformanceRouteChildren: AuthenticatedTeamPerformanceRouteChildren =
  {
    AuthenticatedTeamPerformanceMemberIdRoute:
      AuthenticatedTeamPerformanceMemberIdRoute,
  }

const AuthenticatedTeamPerformanceRouteWithChildren =
  AuthenticatedTeamPerformanceRoute._addFileChildren(
    AuthenticatedTeamPerformanceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBayanRoute: typeof AuthenticatedBayanRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeadlinesRoute: typeof AuthenticatedDeadlinesRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedHearingsRoute: typeof AuthenticatedHearingsRoute
  AuthenticatedOfficePageRoute: typeof AuthenticatedOfficePageRoute
  AuthenticatedPrintLogRoute: typeof AuthenticatedPrintLogRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTeamPerformanceRoute: typeof AuthenticatedTeamPerformanceRouteWithChildren
  AuthenticatedCasesIdRoute: typeof AuthenticatedCasesIdRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBayanRoute: AuthenticatedBayanRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeadlinesRoute: AuthenticatedDeadlinesRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedHearingsRoute: AuthenticatedHearingsRoute,
  AuthenticatedOfficePageRoute: AuthenticatedOfficePageRoute,
  AuthenticatedPrintLogRoute: AuthenticatedPrintLogRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTeamPerformanceRoute:
    AuthenticatedTeamPerformanceRouteWithChildren,
  AuthenticatedCasesIdRoute: AuthenticatedCasesIdRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MehlaAdminSupportRouteChildren {
  MehlaAdminSupportTicketIdRoute: typeof MehlaAdminSupportTicketIdRoute
}

const MehlaAdminSupportRouteChildren: MehlaAdminSupportRouteChildren = {
  MehlaAdminSupportTicketIdRoute: MehlaAdminSupportTicketIdRoute,
}

const MehlaAdminSupportRouteWithChildren =
  MehlaAdminSupportRoute._addFileChildren(MehlaAdminSupportRouteChildren)

interface MehlaAdminRouteRouteChildren {
  MehlaAdminActivityRoute: typeof MehlaAdminActivityRoute
  MehlaAdminAnalyticsRoute: typeof MehlaAdminAnalyticsRoute
  MehlaAdminBackupsRoute: typeof MehlaAdminBackupsRoute
  MehlaAdminContentRoute: typeof MehlaAdminContentRoute
  MehlaAdminCrmRoute: typeof MehlaAdminCrmRoute
  MehlaAdminDesignRoute: typeof MehlaAdminDesignRoute
  MehlaAdminEmailRoute: typeof MehlaAdminEmailRoute
  MehlaAdminFailuresRoute: typeof MehlaAdminFailuresRoute
  MehlaAdminFlagsRoute: typeof MehlaAdminFlagsRoute
  MehlaAdminHrRoute: typeof MehlaAdminHrRoute
  MehlaAdminIntegrationsRoute: typeof MehlaAdminIntegrationsRoute
  MehlaAdminJobsRoute: typeof MehlaAdminJobsRoute
  MehlaAdminLogsRoute: typeof MehlaAdminLogsRoute
  MehlaAdminMailRoute: typeof MehlaAdminMailRoute
  MehlaAdminMarketingRoute: typeof MehlaAdminMarketingRoute
  MehlaAdminMonitoringRoute: typeof MehlaAdminMonitoringRoute
  MehlaAdminNotificationsRoute: typeof MehlaAdminNotificationsRoute
  MehlaAdminOrganizationsRoute: typeof MehlaAdminOrganizationsRoute
  MehlaAdminPlansRoute: typeof MehlaAdminPlansRoute
  MehlaAdminProvidersRoute: typeof MehlaAdminProvidersRoute
  MehlaAdminRbacRoute: typeof MehlaAdminRbacRoute
  MehlaAdminRevenueRoute: typeof MehlaAdminRevenueRoute
  MehlaAdminRolesRoute: typeof MehlaAdminRolesRoute
  MehlaAdminSecurityRoute: typeof MehlaAdminSecurityRoute
  MehlaAdminSeoRoute: typeof MehlaAdminSeoRoute
  MehlaAdminServicesRoute: typeof MehlaAdminServicesRoute
  MehlaAdminSettingsRoute: typeof MehlaAdminSettingsRoute
  MehlaAdminSmsRoute: typeof MehlaAdminSmsRoute
  MehlaAdminStaffRoute: typeof MehlaAdminStaffRoute
  MehlaAdminSubscriptionsRoute: typeof MehlaAdminSubscriptionsRoute
  MehlaAdminSupportRoute: typeof MehlaAdminSupportRouteWithChildren
  MehlaAdminUsersRoute: typeof MehlaAdminUsersRoute
  MehlaAdminIndexRoute: typeof MehlaAdminIndexRoute
  MehlaAdminBillingIdRoute: typeof MehlaAdminBillingIdRoute
  MehlaAdminSalesIdRoute: typeof MehlaAdminSalesIdRoute
  MehlaAdminBillingIndexRoute: typeof MehlaAdminBillingIndexRoute
  MehlaAdminSalesIndexRoute: typeof MehlaAdminSalesIndexRoute
}

const MehlaAdminRouteRouteChildren: MehlaAdminRouteRouteChildren = {
  MehlaAdminActivityRoute: MehlaAdminActivityRoute,
  MehlaAdminAnalyticsRoute: MehlaAdminAnalyticsRoute,
  MehlaAdminBackupsRoute: MehlaAdminBackupsRoute,
  MehlaAdminContentRoute: MehlaAdminContentRoute,
  MehlaAdminCrmRoute: MehlaAdminCrmRoute,
  MehlaAdminDesignRoute: MehlaAdminDesignRoute,
  MehlaAdminEmailRoute: MehlaAdminEmailRoute,
  MehlaAdminFailuresRoute: MehlaAdminFailuresRoute,
  MehlaAdminFlagsRoute: MehlaAdminFlagsRoute,
  MehlaAdminHrRoute: MehlaAdminHrRoute,
  MehlaAdminIntegrationsRoute: MehlaAdminIntegrationsRoute,
  MehlaAdminJobsRoute: MehlaAdminJobsRoute,
  MehlaAdminLogsRoute: MehlaAdminLogsRoute,
  MehlaAdminMailRoute: MehlaAdminMailRoute,
  MehlaAdminMarketingRoute: MehlaAdminMarketingRoute,
  MehlaAdminMonitoringRoute: MehlaAdminMonitoringRoute,
  MehlaAdminNotificationsRoute: MehlaAdminNotificationsRoute,
  MehlaAdminOrganizationsRoute: MehlaAdminOrganizationsRoute,
  MehlaAdminPlansRoute: MehlaAdminPlansRoute,
  MehlaAdminProvidersRoute: MehlaAdminProvidersRoute,
  MehlaAdminRbacRoute: MehlaAdminRbacRoute,
  MehlaAdminRevenueRoute: MehlaAdminRevenueRoute,
  MehlaAdminRolesRoute: MehlaAdminRolesRoute,
  MehlaAdminSecurityRoute: MehlaAdminSecurityRoute,
  MehlaAdminSeoRoute: MehlaAdminSeoRoute,
  MehlaAdminServicesRoute: MehlaAdminServicesRoute,
  MehlaAdminSettingsRoute: MehlaAdminSettingsRoute,
  MehlaAdminSmsRoute: MehlaAdminSmsRoute,
  MehlaAdminStaffRoute: MehlaAdminStaffRoute,
  MehlaAdminSubscriptionsRoute: MehlaAdminSubscriptionsRoute,
  MehlaAdminSupportRoute: MehlaAdminSupportRouteWithChildren,
  MehlaAdminUsersRoute: MehlaAdminUsersRoute,
  MehlaAdminIndexRoute: MehlaAdminIndexRoute,
  MehlaAdminBillingIdRoute: MehlaAdminBillingIdRoute,
  MehlaAdminSalesIdRoute: MehlaAdminSalesIdRoute,
  MehlaAdminBillingIndexRoute: MehlaAdminBillingIndexRoute,
  MehlaAdminSalesIndexRoute: MehlaAdminSalesIndexRoute,
}

const MehlaAdminRouteRouteWithChildren = MehlaAdminRouteRoute._addFileChildren(
  MehlaAdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MehlaAdminRouteRoute: MehlaAdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  PendingAccessRoute: PendingAccessRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiWebhookRoute: ApiWebhookRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
  InviteTokenRoute: InviteTokenRoute,
  OfficeSlugRoute: OfficeSlugRoute,
  PortalSlugRoute: PortalSlugRoute,
  ShareTokenRoute: ShareTokenRoute,
  SignTokenRoute: SignTokenRoute,
  UploadTokenRoute: UploadTokenRoute,
  UploadIndexRoute: UploadIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAiBayanChatRoute: ApiAiBayanChatRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicThemeDotcssRoute: ApiPublicThemeDotcssRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
  ApiIntegrationsOnedriveCallbackRoute: ApiIntegrationsOnedriveCallbackRoute,
  ApiPublicDocTokenRoute: ApiPublicDocTokenRoute,
  ApiPublicHooksCleanupSecureArtifactsRoute:
    ApiPublicHooksCleanupSecureArtifactsRoute,
  ApiPublicHooksEmailDispatchRoute: ApiPublicHooksEmailDispatchRoute,
  ApiPublicHooksEmailInboundRoute: ApiPublicHooksEmailInboundRoute,
  ApiPublicHooksMailSyncRoute: ApiPublicHooksMailSyncRoute,
  ApiPublicHooksNotificationEmailsRoute: ApiPublicHooksNotificationEmailsRoute,
  ApiPublicHooksNotificationsDispatchRoute:
    ApiPublicHooksNotificationsDispatchRoute,
  ApiPublicHooksOperationalRemindersRoute:
    ApiPublicHooksOperationalRemindersRoute,
  ApiPublicHooksOperationalScoreRoute: ApiPublicHooksOperationalScoreRoute,
  ApiPublicOfficeEventRoute: ApiPublicOfficeEventRoute,
  ApiPublicOfficeLeadRoute: ApiPublicOfficeLeadRoute,
  ApiPublicPaymentsProviderRoute: ApiPublicPaymentsProviderRoute,
  ApiPublicWebhooksSlugRoute: ApiPublicWebhooksSlugRoute,
  ApiPublicWhSlugRoute: ApiPublicWhSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  ApiPublicOfficeMediaSplatRoute: ApiPublicOfficeMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
